apiVersion: v1
kind: ConfigMap
data:
{{ (.Files.Glob "files/confd-config/*").AsConfig | indent 2 }}
metadata:
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: '{{ template "kurl.fullname" . }}-confd-config'

---
apiVersion: v1
kind: ConfigMap
data:
{{ (.Files.Glob "files/confd-templates/*").AsConfig | indent 2 }}
metadata:
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: '{{ template "kurl.fullname" . }}-confd-templates'
  namespace: default
